# Site settings
title: Robotica 
tagline: "Sign Language at Scale"
url: "https://robotica.ml/" 

slogans:
  first: Extend your reach to 150,000 additional customers in the UK
  second: |
    Translating your content into British Sign Language for more complete accessibility
    
    Always your best

# Social
socialimg: /images/favicon.png
twitter: roboticaml
github: roboticaml
linkined: roboticaml
logo: /images/logo-transparent.png

# Contact
phone: "01603 290002" 
email: "info@robotica.ml"
address: "Robotica, George Court, Bartholomew's Walk, Ely CB7 4JW"
registration: "12753299"

# Use this for production
sass:
  style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]

permalink: /404.html.

plugins:
  - jekyll-feed
