# Site settings
title: Robotica Machine Learning
tagline: "Automated machine learning, integrated"
url: "https://robotica.ml/" 

# Social
socialimg: /img/social.jpg # be sure to change this image
twitter: roboticaml
github: roboticaml

# Contact
phone: "07958 376942" 
email: "info@robotica.ml"

# Use this for production
#sass:
#    style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
