# Site settings
title: Robotica Machine Learning
tagline: "Automated machine learning, integrated"
url: "https://robotica.ml/" 

slogans:
  first: Make decisions more effectively, more efficiently, more boldly
  second: |
    Fully automated artificial intelligence from Norwich, UK
    
    Always your best

# Social
socialimg: /images/favicon.png
twitter: roboticaml
github: roboticaml
linkined: roboticaml
logo: /images/logo-transparent.png

# Contact
phone: "01603 290002" 
email: "info@robotica.ml"
address: "Robotica, George Court, Bartholomew's Walk, Ely CB7 4JW"
registration: "12753299"

# Use this for production
sass:
  style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]

permalink: /404.html.

plugins:
  - jekyll-feed
