- title: AUTOMATIC DATA COLLECTION
  icon: butterfly.svg
  description: |
    Gathers data from all of your sources

- title: AUTOMATIC CLEANING
  icon: broom.svg
  description: |
    Cleans and enriches data to derive meaning

- title: AUTOMATIC ORCHESTRATION
  icon: violin.svg
  description: |
    Aggregates and composes structure

- title: AUTOMATIC DATA WRANGLING
  icon: lasso.svg
  description: |
    Shapes columns to fit each algorithm

- title: AUTOMATIC MODELLING
  icon: cubes.svg
  description: |
    Unrivalled DataRobot automated modelling

- title: AUTOMATIC EXPLANATIONS
  icon: class.svg
  description: |
    Evaluates, understands and describes

- title: AUTOMATIC GOVERNANCE
  icon: scale-black.svg
  description: |
    Protects the interests of all stakeholders

- title: AUTOMATIC MODEL SELECTION
  icon: touch.svg
  description: |
    Determines which model best fits your needs

- title: AUTOMATIC DEPLOYMENT
  icon: delivery-truck.svg
  description: |
    Models pushed to production seamlessly

- title: AUTOMATIC SCORING
  icon: checklist.svg
  description: |
    APIs, apps and integrations into your business

- title: AUTOMATIC MONITORING
  icon: hot.svg
  description: |
    Protects against data and model drift

- title: AUTOMATIC SELF-IMPROVEMENT
  icon: rotation.svg
  description: |
    Continuous cycle evolves always-best solutions
