- title: END-TO-END AUTOMATION 
  link: "/end-to-end-automation"
  icon: settings.svg
  description: |
    Robotica Machine Learning uniquely delivers fully 
    automated, evolving solutions that stay current.

    From data collection to modelling, evaluation, deployment 
    and beyond. 

- title: AI FOR HIGH-COMPLIANCY ORGANISATIONS 
  link: "/ai-for-high-compliancy-organisations"
  icon: scale.svg
  description: |
    Models that comply with your individual regulations and 
    constraints to ensure compliance with legal, financial, 
    ethical, operational, strategic and reputational demands. 

- title: EMPOWER YOUR PEOPLE, YOUR BUSINESS 
  link: "/empowerment-of-the-enterprise"
  icon: lightning.svg
  description: |
    Enable domain experts to self-serve. \
    Supercharge your data scientists. \
    Gain the benefits of ubiquitous AI at scale.
